// eslint-disable-next-line import/no-anonymous-default-export
export default {
  Elixir : {
    region : "Beaujolais",
    appel : "Côte de Brouilly",
    cepage : "Gamay ",
    conditionnement : "0.75 cL",
    desc : "Une trame aromatique de fruits rouges bien mûrs accompagné d'une subtile nuance vanillée et boisée dûe à l'élevage de 8 mois en fûts de chêne. Vous pouvez le savourer dès à présent ou le déguster dans quelques années selon vos préférences. Découvrez cet élixir du Beaujolais et laissez-vous surprendre par sa complexité.",
    caract : {
      fruite: 3,
      mineral: 1,
      epice: 1, 
      puissance: 3,
      floral: 2,
      boise: 2, 
      acidite: 2,
    },
    garde: "3 à 7 ans (garde moyenne)",
    temp: "12 - 14°C",
    assoc : "Fromages, Hors d’oeuvre chauds et tartes salées, Légumes, Terrines et pâtés, Viandes blanches grillées et rôties, Viandes en sauce claire, Viandes rouges grillées et rôties.",
  },
  Godefroy : {
    region : "Beaujolais",
    appel : "Côte de Brouilly",
    cepage : "Gamay ",
    conditionnement : "0.75 cL",
    desc : "Souple ronde et harmonieuse cette cuvée Godefroy s'ouvre sur un nez relativement discret. La bouche est quant à elle beaucoup plus intense. Des notes de fraises des bois et de framboise s'accordent parfaitement avec sa minéralité et ses tanins fins. La pivoine est également présente en milieu de bouche ce qui apporte un côté floral très flatteur.",
    caract : {
      fruite: 3,
      mineral: 3,
      epice: 1, 
      puissance: 4,
      floral: 2,
      boise: 1, 
      acidite: 2,
    },
    garde: "3 à 7 ans (garde moyenne)",
    temp: "12 - 14°C",
    assoc : "Fromages, Légumes, Pâtes et riz, Terrines et pâtés, Viandes en sauce brune, Viandes rouges grillées et rôties.",
  },
  Brouilly : {
    region : "Beaujolais",
    appel : "Brouilly",
    cepage : "Gamay ",
    conditionnement : "0.75 cL",
    desc : "Voilà un Gamay qui ne manque pas de caractère ! Des notes de mûre, figue et prune confite animent la bouche. Rond, souple et fruité il se veut convivial et harmonieux. Préparez un buffet froid pour accompagner ce vin ou un chapon à la sauce forestière.",
    caract : {
      fruite: 3,
      mineral: 1,
      epice: 1, 
      puissance: 4,
      floral: 2,
      boise: 1, 
      acidite: 3,
    },
    garde: "3 à 7 ans (garde moyenne)",
    temp: "12 - 14°C",
    assoc : "Charcuteries et viandes salées, Hors d'oeuvre froids et salades, Hors d’oeuvre chauds et tartes salées, Pâtes et riz, Terrines et pâtés, Viandes blanches grillées et rôties, Viandes en sauce brune, Viandes en sauce claire, Viandes rouges grillées et rôties",
  },
  CDB : {
    region : "Beaujolais",
    appel : "Côte de Brouilly",
    cepage : "Gamay ",
    conditionnement : "0.75 cL",
    desc : "Ce cru du Beaujolais se caractérise par un fruité intense et une charpente bien présente. Des notes de mûres et de cassis en bouche accompagnent les tanins tendres de ce millésime 2019. Il est élégant et le fruité croquant de ses arômes saura charmer le palais le plus délicat.",
    caract : {
      fruite: 4,
      mineral: 2,
      epice: 1, 
      puissance: 4,
      floral: 2,
      boise: 1, 
      acidite: 2,
    },
    garde: "3 à 7 ans (garde moyenne)",
    temp: "12 - 14°C",
    assoc : "Charcuteries et viandes salées, Hors d'oeuvre froids et salades, Pâtes et riz, Soupes et potages, Terrines et pâtés, Viandes blanches grillées et rôties, Viandes rouges grillées et rôties.",
  },
  Passion : {
    region : "Beaujolais",
    appel : "Beaujolais Village",
    cepage : "Gamay ",
    conditionnement : "0.75 cL",
    desc : "Mordant, frais, ce rosé \"Passion\" du domaine des Fournelles est parfait pour ces chaudes journées d'été qui s'annoncent. Il saura vous rafraichir et vous égayer avec ces notes fruitées et acidulées. La finale autour du bonbon est surprenante et gourmande.",
    caract : {
      fruite: 3,
      mineral: 2,
      epice: 0, 
      puissance: 2,
      floral: 1,
      boise: 0, 
      acidite: 4,
    },
    garde: "1 à 3 ans (à boire jeune)",
    temp: "8 - 10°C",
    assoc : "Apéritif, Hors d'oeuvre froids et salades, Pâtes et riz, Viandes blanches grillées et rôties, Viandes en sauce claire, Œufs.",
  },
  BeaujolaisVillage : {
    region : "Beaujolais",
    appel : "Beaujolais Village",
    cepage : "Gamay ",
    conditionnement : "0.75 cL",
    desc : "Ce Beaujolais Villages élaboré traditionnellement vous surprendra par sa rondeur, son fruité et sa gourmandise. De légères notes de fruits rouges comme la cerise ou la groseille viendront égayer vos papilles. Dégustez le entre amis avec un barbecue ou une plancha et vous serez comblé !",
    caract : {
      fruite: 4,
      mineral: 0,
      epice: 1, 
      puissance: 3,
      floral: 2,
      boise: 0, 
      acidite: 2,
    },
    garde: "1 à 3 ans (à boire jeune)",
    temp: "12 - 14°C",
    assoc : "Charcuteries et viandes salées, Hors d’oeuvre chauds et tartes salées, Légumes, Pâtes et riz, Soupes et potages, Terrines et pâtés, Viandes rouges grillées et rôties",
  },
  SansArtifice : {
    region : "Beaujolais",
    appel : "Brouilly",
    cepage : "Gamay ",
    conditionnement : "0.75 cL",
    desc : "Un somptueux Brouilly sans sulfites ajoutés d'une belle couleur rubis. Des arômes frais et fruités s'ouvrent au nez sur des touches de fruits noirs : myrtille et mûre. Tendue et équilibrée, la bouche révèle une finale délicatement schisteuse et crayeuse apportant du relief à l'ensemble. Une finale longue et droite qui prolonge le plaisir de longues secondes ! L'étiquette et le texte présent sur la contre étiquette ont été pensées en collaboration avec monsieur Dumontet, le vigneron, et Maïa Mazaurette autrice et peintre française très connue du grand public. Autant d'atout invitant à découvrir cette délicieuse cuvée.",
    caract : {
      fruite: 4,
      mineral: 3,
      epice: 0, 
      puissance: 3,
      floral: 1,
      boise: 0, 
      acidite: 2,
    },
    garde: "1 à 3 ans (à boire jeune)",
    temp: "14 - 16°C",
    assoc : "Charcuteries et viandes salées, Desserts, Légumes, Pâtes et riz",
  },
};